export const CALCULATION_BASIS = {
  VENDOR_INVOICE: 'VENDOR_INVOICE',
  VENDOR_INWARD: 'VENDOR_INWARD',
};

export const CALCULATION_BASIS_LABELS = {
  VENDOR_INVOICE: 'Vendor Invoices',
  VENDOR_INWARD: 'GRN',
};

export const INVOICE_ROUTING_MODE = {
  SUPPLY_VENDOR: 'SUPPLY_VENDOR',
  OTHER_VENDOR: 'OTHER_VENDOR',
};
